f = open('C:/Users/RRIMT/Desktop/x1.txt', 'w')
f.write("hello this is second year \n")
f.writelines(["hello \n","welcome\n"])
f.close()
f = open('C:/Users/RRIMT/Desktop/x1.txt', 'a')
f.write("nikal\n")
f.close()
f = open('C:/Users/RRIMT/Desktop/x1.txt', 'r')
print(f.read())